# 텐서 연산자 알아보기 

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.12.0'

In [3]:
x = tf.constant([2,3])

In [4]:
neg_x = tf.negative(x)

In [5]:
neg_x

<tf.Tensor 'Neg:0' shape=(2,) dtype=int32>

### 1. 연산자

In [34]:
sess = tf.Session()

In [7]:
sess.run(neg_x)

array([-2, -3])

In [35]:
sess.run( -x)

array([-2, -3])

In [10]:
sess.run(tf.add(x,x))

array([4, 6])

In [36]:
sess.run(x + x)

array([4, 6])

In [12]:
sess.run(tf.subtract(x,x))

array([0, 0])

In [37]:
sess.run(x - x)

array([0, 0])

In [13]:
sess.run(tf.multiply(x,x))

array([4, 9])

In [38]:
sess.run(x * x)

array([4, 9])

In [14]:
sess.run(tf.div(x,x))

array([1, 1])

In [39]:
sess.run(x//x)

array([1, 1])

In [15]:
sess.run(tf.truediv(x,x))

array([1., 1.])

In [40]:
sess.run(x/x)

array([1., 1.])

In [16]:
sess.run(tf.floordiv(x,x))

array([1, 1])

In [41]:
sess.run(x//x)

array([1, 1])

In [28]:
sess.run(tf.mod(x,x))

array([0, 0])

In [42]:
sess.run(x % x)

array([0, 0])

### 행렬의 곱 처리하기

    rank가 2 이상일 경우만 처리됨. 즉 2차원 배열이상일 경우만 처리

In [54]:
xx= tf.reshape(x,[2,1])

In [55]:
xx

<tf.Tensor 'Reshape:0' shape=(2, 1) dtype=int32>

In [57]:
x1 = tf.reshape(x,[1,2])

In [59]:
sess.run(x1 @ xx)

array([[13]])

In [60]:
sess.run(tf.matmul(x1,xx))

array([[13]])

### 2. 수학함수 

In [18]:
sess.run(tf.pow(x,2))

array([4, 9])

### 타입 변경해서 처리하기

In [30]:
x_f = tf.cast(x, tf.float32)

In [31]:
sess.run(tf.sqrt(x_f))

array([1.4142135, 1.7320508], dtype=float32)

In [23]:
help(tf.exp)

Help on function exp in module tensorflow.python.ops.gen_math_ops:

exp(x, name=None)
    Computes exponential of x element-wise.  \\(y = e^x\\).
    
    Args:
      x: A `Tensor`. Must be one of the following types: `bfloat16`, `half`, `float32`, `float64`, `complex64`, `complex128`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `x`.



In [26]:
sess.run(tf.exp(x_f))

array([ 7.389056, 20.085537], dtype=float32)

In [27]:
sess.run(tf.log(x_f))

array([0.6931472, 1.0986123], dtype=float32)

In [32]:
sess.close()